/**
 * Replay inputs + measured outcomes for the M&V window — Excel rows 2-134 of
 * T1_MVrawDataR2_2025_12_completed.xlsx (2025-12-01 00:00-02:12), the only rows
 * whose `rt` column is MEASURED rather than reconstructed.
 *
 * GENERATED by frontend/scripts/calibrateFromDataset.py — do not hand-edit.
 *
 * Each row now carries the full measured plant state, not just the operator
 * setpoints: achieved CWS, the RH that reproduces the measured wet-bulb, and
 * which units were running. Those are inputs to a historical replay, and
 * withholding them was worth ~2.7% on chiller kW (the twin sat at the 29 degC
 * CWS setpoint while the plant ran nearer 28.5 degC and collected the
 * condenser-lift credit).
 *
 * NOTE ON THIS WINDOW: it is 2.2 hours of Dec-1, and Dec-1 is an outlier day —
 * its CHWP and CT meters read ~22% above the month norm. The engine is now
 * calibrated to the whole month, so it deliberately does NOT reproduce this
 * window as tightly as it used to. Use frontend/scripts/validateMonth.ts for
 * the headline accuracy number.
 */
import { REF_AMBIENT_TEMP, REF_CWS_SP, REF_HUMIDITY_RH } from '../model/plantPhysics';

export interface T1MvRow {
  row: number;
  time: string;
  loadRt: number;
  chwsSp: number;
  /** Achieved condenser water supply (degC) — mean of the running chillers. */
  cwsActual: number;
  /** RH at REF_AMBIENT_TEMP whose Stull wet-bulb equals the measured mean. */
  humidityRh: number;
  cwDtSp: number;
  shares: [number, number, number, number];
  /** Bit u (0-based) set = unit u+1 running. */
  chMask: number;
  chwpMask: number;
  cwpMask: number;
  ctMask: number;
  kw: number;
  kwRt: number;
  deltaT: number;
}

export const T1_MV_ROWS: T1MvRow[] = [
  { row: 2, time: '00:00', loadRt: 3151.0385774808, chwsSp: 7.52, cwsActual: 28.843, humidityRh: 64.026, cwDtSp: 4.3538, shares: [34.382, 18.154, 24.219, 23.246], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1917.69, kwRt: 0.60859, deltaT: 6.55 },
  { row: 3, time: '00:01', loadRt: 3151.0385774808, chwsSp: 7.52, cwsActual: 28.843, humidityRh: 64.026, cwDtSp: 4.3538, shares: [34.354, 18.140, 24.199, 23.307], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1917.69, kwRt: 0.60859, deltaT: 6.55 },
  { row: 4, time: '00:02', loadRt: 3192.0434051749, chwsSp: 7.53, cwsActual: 28.840, humidityRh: 64.148, cwDtSp: 4.4053, shares: [33.168, 20.016, 24.249, 22.567], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1920.20, kwRt: 0.60156, deltaT: 6.64 },
  { row: 5, time: '00:03', loadRt: 3216.0002509525, chwsSp: 7.63, cwsActual: 28.843, humidityRh: 64.173, cwDtSp: 4.4476, shares: [32.820, 20.768, 24.087, 22.325], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1930.32, kwRt: 0.60022, deltaT: 6.69 },
  { row: 6, time: '00:04', loadRt: 3234.9085450668, chwsSp: 7.63, cwsActual: 28.850, humidityRh: 64.075, cwDtSp: 4.4709, shares: [32.827, 20.774, 23.919, 22.479], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1939.99, kwRt: 0.59970, deltaT: 6.73 },
  { row: 7, time: '00:05', loadRt: 3233.6210852431, chwsSp: 7.63, cwsActual: 28.873, humidityRh: 64.271, cwDtSp: 4.4588, shares: [32.883, 20.657, 23.928, 22.532], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1945.03, kwRt: 0.60150, deltaT: 6.72 },
  { row: 8, time: '00:06', loadRt: 3242.1177011658, chwsSp: 7.61, cwsActual: 28.850, humidityRh: 64.197, cwDtSp: 4.4764, shares: [32.802, 20.566, 24.074, 22.558], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1947.91, kwRt: 0.60081, deltaT: 6.73 },
  { row: 9, time: '00:07', loadRt: 3247.4966576059, chwsSp: 7.61, cwsActual: 28.863, humidityRh: 64.209, cwDtSp: 4.4800, shares: [32.680, 20.768, 24.187, 22.364], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1951.50, kwRt: 0.60092, deltaT: 6.74 },
  { row: 10, time: '00:08', loadRt: 3244.8493726471, chwsSp: 7.62, cwsActual: 28.863, humidityRh: 63.978, cwDtSp: 4.4763, shares: [32.743, 20.832, 24.071, 22.354], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1956.96, kwRt: 0.60310, deltaT: 6.74 },
  { row: 11, time: '00:09', loadRt: 3244.3680481092, chwsSp: 7.61, cwsActual: 28.860, humidityRh: 64.087, cwDtSp: 4.4778, shares: [32.772, 20.832, 24.051, 22.345], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1962.23, kwRt: 0.60481, deltaT: 6.74 },
  { row: 12, time: '00:10', loadRt: 3255.6663203867, chwsSp: 7.59, cwsActual: 28.850, humidityRh: 64.100, cwDtSp: 4.4977, shares: [32.772, 20.842, 24.080, 22.306], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1965.24, kwRt: 0.60364, deltaT: 6.77 },
  { row: 13, time: '00:11', loadRt: 3262.4120052317, chwsSp: 7.59, cwsActual: 28.850, humidityRh: 64.051, cwDtSp: 4.4958, shares: [32.739, 20.868, 24.088, 22.305], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1966.35, kwRt: 0.60273, deltaT: 6.78 },
  { row: 14, time: '00:12', loadRt: 3263.9452452659, chwsSp: 7.59, cwsActual: 28.860, humidityRh: 63.966, cwDtSp: 4.5033, shares: [32.679, 20.856, 24.165, 22.300], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1966.15, kwRt: 0.60238, deltaT: 6.78 },
  { row: 15, time: '00:13', loadRt: 3255.5857425647, chwsSp: 7.58, cwsActual: 28.833, humidityRh: 63.856, cwDtSp: 4.4975, shares: [32.892, 20.860, 24.057, 22.191], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1968.63, kwRt: 0.60469, deltaT: 6.77 },
  { row: 16, time: '00:14', loadRt: 3265.5266891669, chwsSp: 7.57, cwsActual: 28.827, humidityRh: 64.026, cwDtSp: 4.5041, shares: [32.854, 20.855, 24.068, 22.223], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1969.18, kwRt: 0.60302, deltaT: 6.79 },
  { row: 17, time: '00:15', loadRt: 3263.1022131931, chwsSp: 7.57, cwsActual: 28.830, humidityRh: 64.014, cwDtSp: 4.5039, shares: [32.785, 20.965, 24.091, 22.159], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1969.05, kwRt: 0.60343, deltaT: 6.79 },
  { row: 18, time: '00:16', loadRt: 3257.0053166904, chwsSp: 7.57, cwsActual: 28.843, humidityRh: 64.075, cwDtSp: 4.4981, shares: [32.825, 20.810, 24.154, 22.210], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1968.37, kwRt: 0.60435, deltaT: 6.78 },
  { row: 19, time: '00:17', loadRt: 3236.6707832243, chwsSp: 7.55, cwsActual: 28.853, humidityRh: 63.929, cwDtSp: 4.4689, shares: [33.555, 19.488, 24.204, 22.754], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1973.14, kwRt: 0.60962, deltaT: 6.73 },
  { row: 20, time: '00:18', loadRt: 3212.1471551891, chwsSp: 7.43, cwsActual: 28.840, humidityRh: 63.710, cwDtSp: 4.4421, shares: [33.801, 18.989, 24.373, 22.837], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1961.31, kwRt: 0.61059, deltaT: 6.68 },
  { row: 21, time: '00:19', loadRt: 3252.1447005971, chwsSp: 7.48, cwsActual: 28.823, humidityRh: 63.868, cwDtSp: 4.5062, shares: [32.806, 20.176, 24.465, 22.553], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1966.21, kwRt: 0.60459, deltaT: 6.76 },
  { row: 22, time: '00:20', loadRt: 3265.2363947683, chwsSp: 7.53, cwsActual: 28.807, humidityRh: 63.771, cwDtSp: 4.5120, shares: [32.725, 20.563, 24.253, 22.459], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1974.43, kwRt: 0.60468, deltaT: 6.78 },
  { row: 23, time: '00:21', loadRt: 3269.1634031277, chwsSp: 7.53, cwsActual: 28.820, humidityRh: 63.746, cwDtSp: 4.5170, shares: [32.649, 20.685, 24.089, 22.576], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1972.93, kwRt: 0.60350, deltaT: 6.79 },
  { row: 24, time: '00:22', loadRt: 3260.8233009952, chwsSp: 7.53, cwsActual: 28.833, humidityRh: 63.929, cwDtSp: 4.5007, shares: [32.638, 20.765, 24.043, 22.554], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1972.13, kwRt: 0.60480, deltaT: 6.77 },
  { row: 25, time: '00:23', loadRt: 3266.6082411146, chwsSp: 7.51, cwsActual: 28.823, humidityRh: 63.905, cwDtSp: 4.5144, shares: [32.487, 20.859, 24.173, 22.481], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1974.78, kwRt: 0.60454, deltaT: 6.78 },
  { row: 26, time: '00:24', loadRt: 3269.4866665908, chwsSp: 7.51, cwsActual: 28.837, humidityRh: 63.917, cwDtSp: 4.5097, shares: [32.550, 20.763, 24.140, 22.547], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1971.34, kwRt: 0.60295, deltaT: 6.79 },
  { row: 27, time: '00:25', loadRt: 3262.6765909013, chwsSp: 7.52, cwsActual: 28.833, humidityRh: 63.990, cwDtSp: 4.5004, shares: [32.645, 20.780, 24.052, 22.523], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1973.72, kwRt: 0.60494, deltaT: 6.77 },
  { row: 28, time: '00:26', loadRt: 3261.9513905033, chwsSp: 7.51, cwsActual: 28.817, humidityRh: 64.319, cwDtSp: 4.5023, shares: [32.571, 20.761, 24.094, 22.574], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1969.84, kwRt: 0.60388, deltaT: 6.77 },
  { row: 29, time: '00:27', loadRt: 3257.6158990048, chwsSp: 7.51, cwsActual: 28.827, humidityRh: 64.319, cwDtSp: 4.5074, shares: [32.602, 20.763, 24.163, 22.472], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1966.41, kwRt: 0.60363, deltaT: 6.76 },
  { row: 30, time: '00:28', loadRt: 3245.0900349161, chwsSp: 7.54, cwsActual: 28.840, humidityRh: 64.356, cwDtSp: 4.4797, shares: [32.557, 20.840, 24.199, 22.404], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1967.31, kwRt: 0.60624, deltaT: 6.74 },
  { row: 31, time: '00:29', loadRt: 3244.4406514643, chwsSp: 7.54, cwsActual: 28.837, humidityRh: 64.319, cwDtSp: 4.4818, shares: [32.725, 20.811, 24.120, 22.343], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1965.42, kwRt: 0.60578, deltaT: 6.73 },
  { row: 32, time: '00:30', loadRt: 3243.2449575206, chwsSp: 7.53, cwsActual: 28.847, humidityRh: 64.283, cwDtSp: 4.4743, shares: [32.568, 20.742, 24.180, 22.510], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1966.29, kwRt: 0.60627, deltaT: 6.74 },
  { row: 33, time: '00:31', loadRt: 3241.3967855559, chwsSp: 7.54, cwsActual: 28.863, humidityRh: 64.051, cwDtSp: 4.4838, shares: [32.679, 20.658, 24.079, 22.585], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1963.29, kwRt: 0.60569, deltaT: 6.73 },
  { row: 34, time: '00:32', loadRt: 3239.5398059710, chwsSp: 7.53, cwsActual: 28.853, humidityRh: 63.831, cwDtSp: 6.7483, shares: [32.475, 20.640, 24.243, 22.642], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1963.16, kwRt: 0.60600, deltaT: 6.72 },
  { row: 35, time: '00:33', loadRt: 3242.0375994313, chwsSp: 7.52, cwsActual: 28.827, humidityRh: 63.917, cwDtSp: 4.4836, shares: [32.631, 20.587, 24.180, 22.602], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1965.27, kwRt: 0.60618, deltaT: 6.73 },
  { row: 36, time: '00:34', loadRt: 3239.3942421951, chwsSp: 7.51, cwsActual: 28.810, humidityRh: 63.953, cwDtSp: 4.4750, shares: [32.648, 20.630, 24.158, 22.564], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1961.98, kwRt: 0.60566, deltaT: 6.73 },
  { row: 37, time: '00:35', loadRt: 3241.4768872903, chwsSp: 7.51, cwsActual: 28.810, humidityRh: 63.868, cwDtSp: 4.4801, shares: [32.476, 20.653, 24.200, 22.671], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1961.55, kwRt: 0.60514, deltaT: 6.73 },
  { row: 38, time: '00:36', loadRt: 3241.2365820870, chwsSp: 7.51, cwsActual: 28.817, humidityRh: 63.758, cwDtSp: 4.4786, shares: [32.421, 20.700, 24.240, 22.639], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1957.50, kwRt: 0.60394, deltaT: 6.73 },
  { row: 39, time: '00:37', loadRt: 3232.0036967302, chwsSp: 7.52, cwsActual: 28.837, humidityRh: 63.905, cwDtSp: 4.4633, shares: [32.461, 20.835, 24.230, 22.475], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1955.48, kwRt: 0.60504, deltaT: 6.71 },
  { row: 40, time: '00:38', loadRt: 3223.1200216093, chwsSp: 7.52, cwsActual: 28.843, humidityRh: 64.674, cwDtSp: 4.4543, shares: [32.583, 20.750, 24.195, 22.472], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1952.56, kwRt: 0.60580, deltaT: 6.70 },
  { row: 41, time: '00:39', loadRt: 3223.0073078760, chwsSp: 7.52, cwsActual: 28.840, humidityRh: 64.649, cwDtSp: 4.4520, shares: [32.387, 20.778, 24.274, 22.562], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1953.58, kwRt: 0.60614, deltaT: 6.69 },
  { row: 42, time: '00:40', loadRt: 3227.4262337219, chwsSp: 7.52, cwsActual: 28.873, humidityRh: 64.527, cwDtSp: 4.4558, shares: [32.346, 20.785, 24.236, 22.632], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1951.03, kwRt: 0.60452, deltaT: 6.70 },
  { row: 43, time: '00:41', loadRt: 3211.1702234859, chwsSp: 7.54, cwsActual: 28.897, humidityRh: 64.539, cwDtSp: 4.4396, shares: [32.263, 20.777, 24.364, 22.595], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1949.70, kwRt: 0.60716, deltaT: 6.66 },
  { row: 44, time: '00:42', loadRt: 3221.2109104350, chwsSp: 7.53, cwsActual: 28.867, humidityRh: 64.711, cwDtSp: 4.4489, shares: [32.252, 20.870, 24.286, 22.591], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1948.88, kwRt: 0.60501, deltaT: 6.68 },
  { row: 45, time: '00:43', loadRt: 3225.7145798692, chwsSp: 7.53, cwsActual: 28.853, humidityRh: 64.845, cwDtSp: 4.4545, shares: [32.406, 20.707, 24.259, 22.627], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1952.65, kwRt: 0.60534, deltaT: 6.69 },
  { row: 46, time: '00:44', loadRt: 3230.4565311345, chwsSp: 7.53, cwsActual: 28.860, humidityRh: 64.882, cwDtSp: 4.4623, shares: [32.398, 20.757, 24.185, 22.659], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1952.33, kwRt: 0.60435, deltaT: 6.70 },
  { row: 47, time: '00:45', loadRt: 3217.3150858118, chwsSp: 7.53, cwsActual: 28.887, humidityRh: 64.698, cwDtSp: 4.4412, shares: [32.396, 20.654, 24.251, 22.698], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1953.01, kwRt: 0.60703, deltaT: 6.68 },
  { row: 48, time: '00:46', loadRt: 3216.4405129372, chwsSp: 7.53, cwsActual: 28.880, humidityRh: 64.466, cwDtSp: 4.4358, shares: [32.322, 20.643, 24.339, 22.695], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1951.86, kwRt: 0.60684, deltaT: 6.68 },
  { row: 49, time: '00:47', loadRt: 3217.3150858118, chwsSp: 7.53, cwsActual: 28.863, humidityRh: 64.319, cwDtSp: 4.4568, shares: [32.336, 20.524, 24.325, 22.815], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1950.84, kwRt: 0.60636, deltaT: 6.68 },
  { row: 50, time: '00:48', loadRt: 3221.0166667046, chwsSp: 7.52, cwsActual: 28.843, humidityRh: 64.454, cwDtSp: 4.4486, shares: [32.348, 20.568, 24.370, 22.714], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1951.29, kwRt: 0.60580, deltaT: 6.69 },
  { row: 51, time: '00:49', loadRt: 3225.6349542224, chwsSp: 7.51, cwsActual: 28.830, humidityRh: 64.466, cwDtSp: 4.4491, shares: [32.350, 20.533, 24.357, 22.760], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1951.37, kwRt: 0.60496, deltaT: 6.69 },
  { row: 52, time: '00:50', loadRt: 3215.5659400625, chwsSp: 7.52, cwsActual: 28.863, humidityRh: 64.417, cwDtSp: 4.4589, shares: [32.368, 20.580, 24.345, 22.706], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1950.98, kwRt: 0.60673, deltaT: 6.68 },
  { row: 53, time: '00:51', loadRt: 3213.8167943133, chwsSp: 7.53, cwsActual: 28.873, humidityRh: 64.466, cwDtSp: 4.4411, shares: [32.443, 20.616, 24.313, 22.628], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1950.64, kwRt: 0.60695, deltaT: 6.68 },
  { row: 54, time: '00:52', loadRt: 3220.7338706852, chwsSp: 7.52, cwsActual: 28.850, humidityRh: 64.246, cwDtSp: 4.4471, shares: [32.456, 20.632, 24.240, 22.671], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1950.91, kwRt: 0.60573, deltaT: 6.68 },
  { row: 55, time: '00:53', loadRt: 3224.0424412852, chwsSp: 7.51, cwsActual: 28.857, humidityRh: 63.953, cwDtSp: 4.4520, shares: [32.396, 20.706, 24.288, 22.610], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1950.74, kwRt: 0.60506, deltaT: 6.69 },
  { row: 56, time: '00:54', loadRt: 3218.1501434177, chwsSp: 7.51, cwsActual: 28.833, humidityRh: 64.161, cwDtSp: 4.4467, shares: [32.406, 20.686, 24.340, 22.568], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1949.05, kwRt: 0.60564, deltaT: 6.69 },
  { row: 57, time: '00:55', loadRt: 3221.9721744669, chwsSp: 7.51, cwsActual: 28.830, humidityRh: 64.283, cwDtSp: 4.4458, shares: [32.414, 20.846, 24.327, 22.413], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1947.45, kwRt: 0.60443, deltaT: 6.69 },
  { row: 58, time: '00:56', loadRt: 3219.8222820017, chwsSp: 7.51, cwsActual: 28.827, humidityRh: 64.466, cwDtSp: 4.4432, shares: [32.372, 20.856, 24.347, 22.425], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1945.65, kwRt: 0.60427, deltaT: 6.69 },
  { row: 59, time: '00:57', loadRt: 3215.6454466875, chwsSp: 7.52, cwsActual: 28.867, humidityRh: 64.490, cwDtSp: 4.4350, shares: [32.375, 20.854, 24.295, 22.476], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1946.50, kwRt: 0.60532, deltaT: 6.68 },
  { row: 60, time: '00:58', loadRt: 3210.2758929770, chwsSp: 7.53, cwsActual: 28.893, humidityRh: 64.271, cwDtSp: 4.4466, shares: [32.278, 20.959, 24.293, 22.470], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1947.39, kwRt: 0.60661, deltaT: 6.67 },
  { row: 61, time: '00:59', loadRt: 3205.7006913847, chwsSp: 7.53, cwsActual: 28.860, humidityRh: 64.332, cwDtSp: 4.4253, shares: [32.428, 20.868, 24.192, 22.512], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1944.94, kwRt: 0.60671, deltaT: 6.66 },
  { row: 62, time: '01:00', loadRt: 3205.2250798976, chwsSp: 7.52, cwsActual: 28.843, humidityRh: 64.197, cwDtSp: 4.4252, shares: [32.415, 20.754, 24.276, 22.556], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1946.12, kwRt: 0.60717, deltaT: 6.66 },
  { row: 63, time: '01:01', loadRt: 3219.0260255331, chwsSp: 7.50, cwsActual: 28.783, humidityRh: 64.100, cwDtSp: 4.4379, shares: [32.284, 20.781, 24.302, 22.633], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1945.48, kwRt: 0.60437, deltaT: 6.69 },
  { row: 64, time: '01:02', loadRt: 3216.2814996872, chwsSp: 7.51, cwsActual: 28.813, humidityRh: 64.002, cwDtSp: 4.4380, shares: [32.383, 20.879, 24.262, 22.476], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1945.17, kwRt: 0.60479, deltaT: 6.68 },
  { row: 65, time: '01:03', loadRt: 3206.5446756326, chwsSp: 7.52, cwsActual: 28.827, humidityRh: 63.795, cwDtSp: 4.4319, shares: [32.421, 20.924, 24.160, 22.495], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1941.51, kwRt: 0.60548, deltaT: 6.67 },
  { row: 66, time: '01:04', loadRt: 3209.4026293432, chwsSp: 7.52, cwsActual: 28.810, humidityRh: 63.795, cwDtSp: 4.4355, shares: [32.215, 20.944, 24.222, 22.619], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1941.53, kwRt: 0.60495, deltaT: 6.67 },
  { row: 67, time: '01:05', loadRt: 3215.6454466875, chwsSp: 7.52, cwsActual: 28.807, humidityRh: 63.795, cwDtSp: 4.4410, shares: [32.311, 20.884, 24.175, 22.631], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1940.66, kwRt: 0.60351, deltaT: 6.68 },
  { row: 68, time: '01:06', loadRt: 3214.9597615582, chwsSp: 7.52, cwsActual: 28.810, humidityRh: 63.783, cwDtSp: 4.4449, shares: [32.242, 20.790, 24.184, 22.784], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1943.77, kwRt: 0.60460, deltaT: 6.67 },
  { row: 69, time: '01:07', loadRt: 3216.2019930623, chwsSp: 7.52, cwsActual: 28.810, humidityRh: 63.734, cwDtSp: 4.4347, shares: [32.230, 20.820, 24.262, 22.688], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1943.17, kwRt: 0.60418, deltaT: 6.68 },
  { row: 70, time: '01:08', loadRt: 3218.8667742394, chwsSp: 7.51, cwsActual: 28.813, humidityRh: 63.406, cwDtSp: 4.4383, shares: [32.493, 20.851, 24.136, 22.519], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1942.10, kwRt: 0.60335, deltaT: 6.69 },
  { row: 71, time: '01:09', loadRt: 3218.1501434177, chwsSp: 7.51, cwsActual: 28.823, humidityRh: 63.199, cwDtSp: 4.4375, shares: [32.231, 20.911, 24.291, 22.567], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1941.79, kwRt: 0.60339, deltaT: 6.69 },
  { row: 72, time: '01:10', loadRt: 3215.5659400625, chwsSp: 7.52, cwsActual: 28.813, humidityRh: 62.835, cwDtSp: 4.4334, shares: [32.251, 20.933, 24.215, 22.601], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1940.88, kwRt: 0.60359, deltaT: 6.68 },
  { row: 73, time: '01:11', loadRt: 3220.0611589423, chwsSp: 7.51, cwsActual: 28.777, humidityRh: 62.569, cwDtSp: 4.4431, shares: [32.318, 20.985, 24.090, 22.608], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1940.28, kwRt: 0.60256, deltaT: 6.69 },
  { row: 74, time: '01:12', loadRt: 3222.3225749218, chwsSp: 7.50, cwsActual: 28.780, humidityRh: 62.484, cwDtSp: 4.4526, shares: [32.328, 20.955, 24.119, 22.597], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1938.45, kwRt: 0.60157, deltaT: 6.70 },
  { row: 75, time: '01:13', loadRt: 3223.9174682968, chwsSp: 7.49, cwsActual: 28.760, humidityRh: 62.605, cwDtSp: 4.4447, shares: [32.207, 20.960, 24.217, 22.616], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1938.56, kwRt: 0.60131, deltaT: 6.70 },
  { row: 76, time: '01:14', loadRt: 3228.6494217231, chwsSp: 7.48, cwsActual: 28.750, humidityRh: 62.557, cwDtSp: 4.4600, shares: [32.331, 20.843, 24.149, 22.677], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1937.49, kwRt: 0.60009, deltaT: 6.71 },
  { row: 77, time: '01:15', loadRt: 3212.3061684390, chwsSp: 7.49, cwsActual: 28.773, humidityRh: 62.642, cwDtSp: 4.4364, shares: [32.244, 20.912, 24.182, 22.661], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.68, kwRt: 0.60289, deltaT: 6.68 },
  { row: 78, time: '01:16', loadRt: 3218.6278972988, chwsSp: 7.49, cwsActual: 28.780, humidityRh: 62.799, cwDtSp: 4.4429, shares: [32.412, 20.842, 24.087, 22.659], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1937.16, kwRt: 0.60186, deltaT: 6.69 },
  { row: 79, time: '01:17', loadRt: 3223.0073078760, chwsSp: 7.49, cwsActual: 28.777, humidityRh: 62.872, cwDtSp: 4.4412, shares: [32.009, 20.999, 24.089, 22.903], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1935.35, kwRt: 0.60048, deltaT: 6.69 },
  { row: 80, time: '01:18', loadRt: 3212.1471551891, chwsSp: 7.50, cwsActual: 28.773, humidityRh: 62.969, cwDtSp: 4.4377, shares: [32.244, 20.974, 24.134, 22.648], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1935.85, kwRt: 0.60267, deltaT: 6.68 },
  { row: 81, time: '01:19', loadRt: 3215.0093936878, chwsSp: 7.50, cwsActual: 28.790, humidityRh: 63.102, cwDtSp: 4.4343, shares: [32.329, 21.020, 24.110, 22.542], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1934.12, kwRt: 0.60159, deltaT: 6.68 },
  { row: 82, time: '01:20', loadRt: 3205.7799599659, chwsSp: 7.50, cwsActual: 28.797, humidityRh: 63.090, cwDtSp: 4.4276, shares: [32.295, 21.010, 24.111, 22.584], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1935.37, kwRt: 0.60371, deltaT: 6.66 },
  { row: 83, time: '01:21', loadRt: 3206.7828384418, chwsSp: 7.50, cwsActual: 28.790, humidityRh: 63.163, cwDtSp: 4.4419, shares: [32.390, 20.990, 24.080, 22.540], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1934.17, kwRt: 0.60315, deltaT: 6.67 },
  { row: 84, time: '01:22', loadRt: 3207.3653315894, chwsSp: 7.50, cwsActual: 28.800, humidityRh: 63.466, cwDtSp: 4.4327, shares: [32.233, 21.041, 24.188, 22.537], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1934.52, kwRt: 0.60315, deltaT: 6.66 },
  { row: 85, time: '01:23', loadRt: 3200.1518907023, chwsSp: 7.50, cwsActual: 28.807, humidityRh: 63.685, cwDtSp: 4.4205, shares: [32.342, 21.042, 24.140, 22.476], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1934.30, kwRt: 0.60444, deltaT: 6.66 },
  { row: 86, time: '01:24', loadRt: 3212.1471551891, chwsSp: 7.50, cwsActual: 28.810, humidityRh: 63.941, cwDtSp: 4.4272, shares: [32.285, 21.051, 24.088, 22.577], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.09, kwRt: 0.60274, deltaT: 6.68 },
  { row: 87, time: '01:25', loadRt: 3206.4933771965, chwsSp: 7.51, cwsActual: 28.837, humidityRh: 64.002, cwDtSp: 4.4236, shares: [32.298, 21.004, 24.167, 22.530], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.15, kwRt: 0.60382, deltaT: 6.66 },
  { row: 88, time: '01:26', loadRt: 3200.7067707705, chwsSp: 7.51, cwsActual: 28.853, humidityRh: 63.746, cwDtSp: 4.4170, shares: [32.262, 20.994, 24.113, 22.631], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.79, kwRt: 0.60511, deltaT: 6.66 },
  { row: 89, time: '01:27', loadRt: 3200.5707287461, chwsSp: 7.52, cwsActual: 28.863, humidityRh: 63.880, cwDtSp: 4.4138, shares: [32.244, 20.865, 24.204, 22.686], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1935.66, kwRt: 0.60479, deltaT: 6.65 },
  { row: 90, time: '01:28', loadRt: 3197.0089985783, chwsSp: 7.51, cwsActual: 28.827, humidityRh: 63.783, cwDtSp: 4.4241, shares: [32.209, 20.867, 24.190, 22.734], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.73, kwRt: 0.60579, deltaT: 6.65 },
  { row: 91, time: '01:29', loadRt: 3198.9877375604, chwsSp: 7.50, cwsActual: 28.817, humidityRh: 63.966, cwDtSp: 4.4224, shares: [32.226, 20.900, 24.272, 22.602], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1937.14, kwRt: 0.60555, deltaT: 6.65 },
  { row: 92, time: '01:30', loadRt: 3201.3622243389, chwsSp: 7.50, cwsActual: 28.830, humidityRh: 63.966, cwDtSp: 4.4276, shares: [32.182, 21.004, 24.174, 22.640], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1940.07, kwRt: 0.60601, deltaT: 6.65 },
  { row: 93, time: '01:31', loadRt: 3195.7578404322, chwsSp: 7.51, cwsActual: 28.883, humidityRh: 64.148, cwDtSp: 4.4120, shares: [32.227, 21.012, 24.294, 22.467], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1937.57, kwRt: 0.60629, deltaT: 6.64 },
  { row: 94, time: '01:32', loadRt: 3190.9449521183, chwsSp: 7.51, cwsActual: 28.873, humidityRh: 64.258, cwDtSp: 4.4057, shares: [32.333, 20.936, 24.280, 22.451], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.02, kwRt: 0.60672, deltaT: 6.63 },
  { row: 95, time: '01:33', loadRt: 3183.8470814899, chwsSp: 7.51, cwsActual: 28.877, humidityRh: 63.978, cwDtSp: 4.4005, shares: [32.252, 20.968, 24.276, 22.505], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1936.45, kwRt: 0.60821, deltaT: 6.62 },
  { row: 96, time: '01:34', loadRt: 3192.2075363662, chwsSp: 7.50, cwsActual: 28.880, humidityRh: 63.649, cwDtSp: 4.4202, shares: [32.297, 20.938, 24.238, 22.527], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1933.62, kwRt: 0.60573, deltaT: 6.63 },
  { row: 97, time: '01:35', loadRt: 3178.5656039807, chwsSp: 7.50, cwsActual: 28.810, humidityRh: 63.661, cwDtSp: 4.3906, shares: [32.328, 20.851, 24.320, 22.501], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1932.25, kwRt: 0.60790, deltaT: 6.61 },
  { row: 98, time: '01:36', loadRt: 3198.1170924083, chwsSp: 7.47, cwsActual: 28.760, humidityRh: 63.649, cwDtSp: 4.4152, shares: [32.214, 20.984, 24.348, 22.454], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1928.27, kwRt: 0.60294, deltaT: 6.65 },
  { row: 99, time: '01:37', loadRt: 3192.9917716235, chwsSp: 7.47, cwsActual: 28.753, humidityRh: 63.637, cwDtSp: 4.4032, shares: [32.197, 20.982, 24.364, 22.456], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1924.61, kwRt: 0.60276, deltaT: 6.64 },
  { row: 100, time: '01:38', loadRt: 3174.9466242821, chwsSp: 7.50, cwsActual: 28.800, humidityRh: 63.539, cwDtSp: 4.3913, shares: [32.109, 21.044, 24.410, 22.436], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1922.65, kwRt: 0.60557, deltaT: 6.61 },
  { row: 101, time: '01:39', loadRt: 3175.9693794143, chwsSp: 7.50, cwsActual: 28.813, humidityRh: 63.783, cwDtSp: 4.3819, shares: [32.193, 20.929, 24.385, 22.493], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1920.62, kwRt: 0.60474, deltaT: 6.61 },
  { row: 102, time: '01:40', loadRt: 3175.5760120557, chwsSp: 7.50, cwsActual: 28.803, humidityRh: 63.844, cwDtSp: 4.3849, shares: [32.450, 20.824, 24.307, 22.419], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1920.19, kwRt: 0.60467, deltaT: 6.61 },
  { row: 103, time: '01:41', loadRt: 3175.2494159795, chwsSp: 7.50, cwsActual: 28.817, humidityRh: 64.063, cwDtSp: 4.3816, shares: [32.167, 20.960, 24.316, 22.557], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1919.25, kwRt: 0.60444, deltaT: 6.60 },
  { row: 104, time: '01:42', loadRt: 3165.1832583452, chwsSp: 7.50, cwsActual: 28.813, humidityRh: 64.185, cwDtSp: 4.3702, shares: [32.300, 20.879, 24.255, 22.566], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1922.42, kwRt: 0.60736, deltaT: 6.59 },
  { row: 105, time: '01:43', loadRt: 3164.5557749218, chwsSp: 7.50, cwsActual: 28.867, humidityRh: 64.100, cwDtSp: 4.3685, shares: [32.221, 20.927, 24.308, 22.543], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1923.71, kwRt: 0.60789, deltaT: 6.59 },
  { row: 106, time: '01:44', loadRt: 3152.9604239977, chwsSp: 7.53, cwsActual: 28.927, humidityRh: 64.100, cwDtSp: 4.3554, shares: [32.386, 20.990, 24.241, 22.383], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1922.76, kwRt: 0.60983, deltaT: 6.56 },
  { row: 107, time: '01:45', loadRt: 3166.8304023315, chwsSp: 7.51, cwsActual: 28.850, humidityRh: 64.063, cwDtSp: 4.3803, shares: [32.345, 21.116, 24.268, 22.271], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1924.72, kwRt: 0.60777, deltaT: 6.59 },
  { row: 108, time: '01:46', loadRt: 3175.4973385840, chwsSp: 7.48, cwsActual: 28.827, humidityRh: 63.856, cwDtSp: 4.3820, shares: [32.198, 21.139, 24.333, 22.330], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1921.72, kwRt: 0.60517, deltaT: 6.61 },
  { row: 109, time: '01:47', loadRt: 3178.5656039807, chwsSp: 7.49, cwsActual: 28.783, humidityRh: 63.771, cwDtSp: 4.3860, shares: [32.066, 21.100, 24.372, 22.461], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1916.62, kwRt: 0.60298, deltaT: 6.61 },
  { row: 110, time: '01:48', loadRt: 3175.8907059426, chwsSp: 7.49, cwsActual: 28.753, humidityRh: 63.649, cwDtSp: 4.3822, shares: [32.294, 21.143, 24.290, 22.273], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1913.30, kwRt: 0.60245, deltaT: 6.61 },
  { row: 111, time: '01:49', loadRt: 3179.9074568098, chwsSp: 7.48, cwsActual: 28.760, humidityRh: 63.527, cwDtSp: 4.3908, shares: [32.217, 21.222, 24.299, 22.262], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1913.41, kwRt: 0.60172, deltaT: 6.62 },
  { row: 112, time: '01:50', loadRt: 3169.1221688939, chwsSp: 7.49, cwsActual: 28.790, humidityRh: 63.454, cwDtSp: 4.3738, shares: [32.371, 21.069, 24.214, 22.346], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1913.26, kwRt: 0.60372, deltaT: 6.60 },
  { row: 113, time: '01:51', loadRt: 3166.4382251919, chwsSp: 7.49, cwsActual: 28.797, humidityRh: 63.442, cwDtSp: 4.3725, shares: [32.152, 21.201, 24.203, 22.444], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1909.74, kwRt: 0.60312, deltaT: 6.59 },
  { row: 114, time: '01:52', loadRt: 3174.8679508104, chwsSp: 7.49, cwsActual: 28.773, humidityRh: 63.649, cwDtSp: 4.3812, shares: [32.163, 21.249, 24.238, 22.349], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1911.20, kwRt: 0.60198, deltaT: 6.61 },
  { row: 115, time: '01:53', loadRt: 3172.9713369349, chwsSp: 7.49, cwsActual: 28.787, humidityRh: 64.063, cwDtSp: 4.3892, shares: [32.177, 21.231, 24.233, 22.358], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1911.65, kwRt: 0.60248, deltaT: 6.60 },
  { row: 116, time: '01:54', loadRt: 3167.7081887973, chwsSp: 7.51, cwsActual: 28.820, humidityRh: 64.161, cwDtSp: 4.3654, shares: [32.172, 21.331, 24.160, 22.337], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1909.80, kwRt: 0.60290, deltaT: 6.60 },
  { row: 117, time: '01:55', loadRt: 3149.2907409724, chwsSp: 7.53, cwsActual: 28.903, humidityRh: 64.405, cwDtSp: 4.3527, shares: [32.167, 21.283, 24.214, 22.336], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1909.64, kwRt: 0.60637, deltaT: 6.56 },
  { row: 118, time: '01:56', loadRt: 3155.5246316747, chwsSp: 7.52, cwsActual: 28.877, humidityRh: 63.917, cwDtSp: 4.3607, shares: [32.206, 21.282, 24.175, 22.338], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1911.36, kwRt: 0.60572, deltaT: 6.58 },
  { row: 119, time: '01:57', loadRt: 3156.9343269832, chwsSp: 7.51, cwsActual: 28.850, humidityRh: 63.783, cwDtSp: 4.3651, shares: [32.112, 21.310, 24.233, 22.344], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1911.55, kwRt: 0.60551, deltaT: 6.58 },
  { row: 120, time: '01:58', loadRt: 3170.7769302815, chwsSp: 7.49, cwsActual: 28.810, humidityRh: 63.722, cwDtSp: 4.3674, shares: [32.109, 21.382, 24.270, 22.238], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1912.11, kwRt: 0.60304, deltaT: 6.61 },
  { row: 121, time: '01:59', loadRt: 3166.3727631504, chwsSp: 7.49, cwsActual: 28.790, humidityRh: 63.588, cwDtSp: 4.3638, shares: [32.199, 21.359, 24.271, 22.170], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1910.00, kwRt: 0.60321, deltaT: 6.60 },
  { row: 122, time: '02:00', loadRt: 3159.6143429628, chwsSp: 7.50, cwsActual: 28.813, humidityRh: 63.503, cwDtSp: 4.3624, shares: [32.203, 21.370, 24.261, 22.166], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1907.41, kwRt: 0.60368, deltaT: 6.59 },
  { row: 123, time: '02:01', loadRt: 3154.1932527723, chwsSp: 7.49, cwsActual: 28.797, humidityRh: 63.661, cwDtSp: 4.3689, shares: [32.186, 21.254, 24.289, 22.271], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1907.63, kwRt: 0.60479, deltaT: 6.58 },
  { row: 124, time: '02:02', loadRt: 3150.8071989195, chwsSp: 7.50, cwsActual: 28.800, humidityRh: 63.552, cwDtSp: 6.5380, shares: [32.235, 21.173, 24.342, 22.250], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1907.02, kwRt: 0.60525, deltaT: 6.57 },
  { row: 125, time: '02:03', loadRt: 3152.2147518339, chwsSp: 7.48, cwsActual: 28.800, humidityRh: 63.491, cwDtSp: 4.3511, shares: [32.277, 21.066, 24.358, 22.299], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1904.45, kwRt: 0.60416, deltaT: 6.57 },
  { row: 126, time: '02:04', loadRt: 3151.7455675291, chwsSp: 7.48, cwsActual: 28.787, humidityRh: 63.296, cwDtSp: 4.3482, shares: [32.314, 21.070, 24.342, 22.274], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1904.11, kwRt: 0.60414, deltaT: 6.57 },
  { row: 127, time: '02:05', loadRt: 3148.1195655388, chwsSp: 7.48, cwsActual: 28.790, humidityRh: 63.223, cwDtSp: 4.3537, shares: [32.492, 21.035, 24.261, 22.212], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1900.10, kwRt: 0.60357, deltaT: 6.56 },
  { row: 128, time: '02:06', loadRt: 3140.8259038954, chwsSp: 7.48, cwsActual: 28.803, humidityRh: 63.078, cwDtSp: 4.3388, shares: [32.567, 21.109, 24.063, 22.261], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1899.85, kwRt: 0.60489, deltaT: 6.55 },
  { row: 129, time: '02:07', loadRt: 3127.2940667614, chwsSp: 7.49, cwsActual: 28.803, humidityRh: 63.406, cwDtSp: 4.3273, shares: [32.547, 21.187, 23.856, 22.411], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1889.02, kwRt: 0.60404, deltaT: 6.52 },
  { row: 130, time: '02:08', loadRt: 3123.7373355132, chwsSp: 7.49, cwsActual: 28.800, humidityRh: 63.527, cwDtSp: 4.3111, shares: [32.541, 21.085, 23.928, 22.445], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1892.89, kwRt: 0.60597, deltaT: 6.51 },
  { row: 131, time: '02:09', loadRt: 3118.5521467160, chwsSp: 7.49, cwsActual: 28.810, humidityRh: 63.393, cwDtSp: 4.3065, shares: [32.588, 21.092, 23.837, 22.483], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1891.64, kwRt: 0.60658, deltaT: 6.50 },
  { row: 132, time: '02:10', loadRt: 3123.4274025021, chwsSp: 7.48, cwsActual: 28.820, humidityRh: 63.600, cwDtSp: 4.3186, shares: [32.511, 21.124, 23.847, 22.518], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1891.90, kwRt: 0.60571, deltaT: 6.51 },
  { row: 133, time: '02:11', loadRt: 3108.4244547626, chwsSp: 7.49, cwsActual: 28.813, humidityRh: 63.698, cwDtSp: 4.2943, shares: [32.637, 21.095, 23.861, 22.408], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1888.90, kwRt: 0.60767, deltaT: 6.49 },
  { row: 134, time: '02:12', loadRt: 3114.6839351720, chwsSp: 7.49, cwsActual: 28.810, humidityRh: 63.783, cwDtSp: 4.3067, shares: [32.566, 21.089, 23.864, 22.481], chMask: 14, chwpMask: 14, cwpMask: 14, ctMask: 27, kw: 1884.93, kwRt: 0.60518, deltaT: 6.50 },
];

export const mvRowById = (scenarioId: string | undefined): T1MvRow | undefined => {
  const m = /^row-(\d+)$/.exec(scenarioId ?? '');
  return m ? T1_MV_ROWS.find((r) => r.row === Number(m[1])) : undefined;
};

/** Bitmask -> duty order: running units first, then the standby units. */
export function dutyFromMask(mask: number, count: number): number[] {
  const on: number[] = [];
  const off: number[] = [];
  for (let u = 1; u <= count; u++) ((mask >> (u - 1)) & 1 ? on : off).push(u);
  return [...on, ...off];
}

const popcount = (mask: number): number => {
  let n = 0;
  for (let m = mask; m; m >>= 1) n += m & 1;
  return n;
};

/** Measured plant state a replay row can pin beyond the operator inputs. */
export interface RowReplayOverrides {
  cwsActual?: number;
  humidityRh?: number;
  duty?: Partial<Record<'chiller' | 'chwp' | 'cwp' | 'ct', number[]>>;
  staging?: Partial<Record<'chiller' | 'chwp' | 'cwp' | 'ct', number>>;
  /** Ignore the row's own measured CWS / wet-bulb / staging and use the twin's
   *  reference weather and load-driven staging instead. */
  inputsOnly?: boolean;
}

/**
 * Scenario payload replaying one dataset row. By default every measured input
 * the row carries is fed through; pass inputsOnly to fall back to the twin's
 * own reference weather and staging rules.
 */
export function buildRowReplayPayload(r: T1MvRow, overrides: RowReplayOverrides = {}) {
  const bare = overrides.inputsOnly === true;
  return {
    id: `row-${r.row}`,
    label: `Dataset row ${r.row} (${r.time})`,
    precise: true,
    duty: overrides.duty ?? (bare ? undefined : {
      chiller: dutyFromMask(r.chMask, 5),
      chwp: dutyFromMask(r.chwpMask, 6),
      cwp: dutyFromMask(r.cwpMask, 6),
      ct: dutyFromMask(r.ctMask, 5),
    }),
    staging: overrides.staging ?? (bare ? undefined : {
      chiller: popcount(r.chMask),
      chwp: popcount(r.chwpMask),
      cwp: popcount(r.cwpMask),
      ct: popcount(r.ctMask),
    }),
    controls: {
      'ctrl-building-load': r.loadRt,
      'ctrl-chws-sp': r.chwsSp,
      'ctrl-cw-dt-sp': r.cwDtSp,
      'ctrl-riser-finger': r.shares[0],
      'ctrl-riser-l13': r.shares[1],
      'ctrl-riser-main': r.shares[2],
      'ctrl-riser-t1u': r.shares[3],
      'ctrl-ambient-temp': REF_AMBIENT_TEMP,
      'ctrl-humidity': overrides.humidityRh ?? (bare ? REF_HUMIDITY_RH : r.humidityRh),
      // The CWS setpoint doubles as the achieved CWS in static mode, so feeding
      // the measured value is what puts the chiller on its real condenser lift.
      'ctrl-cws-sp': overrides.cwsActual ?? (bare ? REF_CWS_SP : r.cwsActual),
      'ctrl-dp-sp': 15,
      'ctrl-dp-sp-high': 12,
      'ctrl-ct-fan': 0,
      'ctrl-pump-spd': 0,
      'ctrl-cwp-spd': 0,
      'ctrl-ch-enable': 1,
    },
    advanceSec: 0,
  };
}
