/**
 * Per-unit characterization of the real T1 plant.
 *
 * CALIBRATION BASIS CHANGED 2026-08-07: every constant below now comes from the
 * WHOLE Dec-2025 trend (43,026 usable rows of T1_MVrawDataR2_2025_12_completed
 * .xlsx) instead of from its first row. See t1MonthCalibration.ts — generated by
 * frontend/scripts/calibrateFromDataset.py — for the fit itself.
 *
 * Why the change: the previous constants were anchored to Dec-1 00:00, and that
 * row turned out to be an outlier. Its CHWP and CT meters read ~22% above every
 * other day of the month, so replaying any other row over-read plant kW by that
 * margin on those blocks (+3.86% MAE month-wide). Re-fitting against the full
 * month takes the same physics to 0.83% blocked-CV MAE.
 *
 * This file is now a thin, STABLE naming layer over the generated constants: it
 * keeps the export names the engine and UI already import, and does the small
 * amount of reshaping the engine's data structures need (per-compressor standby
 * split, riser metadata records). No numbers are invented here.
 */
import {
  CH_KW_INTERCEPT as CH_KW_INTERCEPT_GEN,
  CH_KW_SLOPE_PER_PCT as CH_KW_SLOPE_PER_PCT_GEN,
  CH_TRIM_MONTH,
  CHWP_TRIM_MONTH,
  CWP_TRIM_MONTH,
  CT_TRIM_MONTH,
  CH_CP1_SHARE_MONTH,
  HL_CP_RATIO_MONTH,
  CHWP_VSD_RATIO_MONTH,
  CWP_VSD_RATIO_MONTH,
  CH_STANDBY_KW_MONTH,
  CHWP_STANDBY_KW_MONTH,
  CWP_STANDBY_KW_MONTH,
  CT_CELL_KW_FRAC_MONTH,
  CH_SENSOR_OFFSET_MONTH,
  CH_STAGNANT_MONTH,
  CH_EVAP_FLOW_TRIM_MONTH,
  CH_COND_FLOW_TRIM_MONTH,
  CT_CELL_OFFSET_MONTH,
  CT_STAGNANT_MONTH,
  RISER_LOAD_SHARE_MONTH,
  RISER_FLOW_FRAC_MONTH,
  RISER_ST_OFFSET_MONTH,
  RISER_RT_OFFSET_MONTH,
  WST_OFFSET_MONTH,
  DUTY_ORDER_MONTH,
  DEFAULT_LOAD_RT,
  DEFAULT_CHWS_SP,
  DEFAULT_CW_DT_SP,
} from '../calibration/t1MonthCalibration';

/* ------------------------- Default operating point ------------------------ */

/** Boot load / setpoints — the month's median operating point. */
export const ROW1_LOAD_RT = DEFAULT_LOAD_RT;
export const ROW1_CHWS_SP = DEFAULT_CHWS_SP;
export const ROW1_CW_DT_SP = DEFAULT_CW_DT_SP;

/* ------------------------------ Duty rotation ----------------------------- */

/**
 * Duty order — staging count N runs the FIRST N units of each order. Ordered by
 * how often each unit actually ran over the month, so the default running set is
 * the plant's own most-common one (CH-3/5/4, not the row-1 CH-2/3/4).
 */
export const DUTY_DEFAULTS = {
  chiller: [...DUTY_ORDER_MONTH.chiller],
  chwp: [...DUTY_ORDER_MONTH.chwp],
  cwp: [...DUTY_ORDER_MONTH.cwp],
  ct: [...DUTY_ORDER_MONTH.ct],
} as const;

export type DutyCategory = keyof typeof DUTY_DEFAULTS;

/* --------------------------- Per-unit kW trims ---------------------------- */

/** Each unit's median draw while running, over its category's reference. */
export const CH_TRIM = CH_TRIM_MONTH;
export const CHWP_TRIM = CHWP_TRIM_MONTH;
export const CWP_TRIM = CWP_TRIM_MONTH;
export const CT_TRIM = CT_TRIM_MONTH;

/** Compressor-1 share of each chiller's DPM total. */
export const CH_CP1_SHARE = CH_CP1_SHARE_MONTH;

/** HL heat-load meter ÷ DPM feeder meter, per compressor (HL reads ~6% low). */
export const HL_CP_RATIO = HL_CP_RATIO_MONTH;

/** VSD kW readout ÷ DPM feeder meter, per pump. */
export const CHWP_VSD_RATIO = CHWP_VSD_RATIO_MONTH;
export const CWP_VSD_RATIO = CWP_VSD_RATIO_MONTH;

/**
 * Parasitic draw of STOPPED units. The engine tracks the two compressors of a
 * chiller separately, so the measured per-unit standby total is split by that
 * unit's CP-1 share.
 */
export const CH_STANDBY_KW = CH_STANDBY_KW_MONTH.map((kw, i) => ({
  cp1: kw * (CH_CP1_SHARE_MONTH[i] ?? 0.5),
  cp2: kw * (1 - (CH_CP1_SHARE_MONTH[i] ?? 0.5)),
}));
export const CHWP_STANDBY_KW = CHWP_STANDBY_KW_MONTH;
export const CWP_STANDBY_KW = CWP_STANDBY_KW_MONTH;

/** Tower cell VSD kW as fractions of the tower's DPM meter (sum < 1). */
export const CT_CELL_KW_FRAC = CT_CELL_KW_FRAC_MONTH;

/* ---------------------------- Sensor behaviour ---------------------------- */

/** Offsets of a RUNNING chiller's sensors against the plant headers (°C). */
export const CH_SENSOR_OFFSET = CH_SENSOR_OFFSET_MONTH;

/** Readings a STOPPED chiller's stagnant sensors settle at. */
export const CH_STAGNANT = CH_STAGNANT_MONTH;

/** Per-chiller flow-meter trims against an even split of the loop / CW flow. */
export const CH_EVAP_FLOW_TRIM = CH_EVAP_FLOW_TRIM_MONTH;
export const CH_COND_FLOW_TRIM = CH_COND_FLOW_TRIM_MONTH;

/** Tower cell temp offsets against the plant CWS/CWR headers ([A, B] per tower). */
export const CT_CELL_OFFSET = CT_CELL_OFFSET_MONTH;

/** Stagnant cell readings for a stopped tower. */
export const CT_STAGNANT = CT_STAGNANT_MONTH;

/** Per-sensor wet-bulb bias against the five-sensor mean. */
export const WST_OFFSET = WST_OFFSET_MONTH;

/* -------------------------------- Risers ---------------------------------- */

/** Riser load split (% of building load) — control defaults. */
export const RISER_LOAD_SHARE_DEFAULT = RISER_LOAD_SHARE_MONTH;

const RISER_META = [
  { id: 'riser-finger', name: 'Finger', controlId: 'ctrl-riser-finger' },
  { id: 'riser-l13', name: 'L1-3', controlId: 'ctrl-riser-l13' },
  { id: 'riser-main', name: 'MainBuilding', controlId: 'ctrl-riser-main' },
  { id: 'riser-t1u', name: 'T1U', controlId: 'ctrl-riser-t1u' },
];

/** The four CHW risers: measured share of loop flow, plus the sensor offsets
 *  that reconcile each riser's own energy balance with its measured temps. */
export const RISERS = RISER_META.map((m, i) => ({
  ...m,
  flowFrac: RISER_FLOW_FRAC_MONTH[i],
  stOff: RISER_ST_OFFSET_MONTH[i],
  rtOff: RISER_RT_OFFSET_MONTH[i],
}));

/* --------------------- Chiller part-load curve (affine) -------------------
 * Real chiller kW is AFFINE in load, not proportional: measured efficiency
 * improves as load rises. Least-squares fit of per-chiller kW (with the
 * evaporator-reset and condenser-lift factors divided out) against per-chiller
 * load %, over all 43,026 usable month rows — loadPct 73–88%.
 *
 * A refit is not what fixed the month-wide error: the OLD curve already scored
 * 0.51% on held-out days. The error lived in the pump/tower reference levels and
 * in pinning CWS at setpoint instead of feeding the measured value. */
export const CH_KW_SLOPE_PER_PCT = CH_KW_SLOPE_PER_PCT_GEN;
export const CH_KW_INTERCEPT = CH_KW_INTERCEPT_GEN;
