/**
 * Gordon-Ng chiller power model fitted to the real T1 December trend —
 * GENERATED by `calibration/scripts/fitGordonNg.py`. Do not hand-edit.
 *
 *     P = [Q*(Tcds - Tchs) + a1*Tcds*Tchs + a2*(Tcds - Tchs) + a3*Q^2]
 *         / (Tchs - a4*Q)              Q, P in kW; temperatures in KELVIN
 *
 * WHY THE TWIN KEEPS BOTH THIS AND THE AFFINE CURVE
 * -------------------------------------------------
 * The engine's affine part-load curve is the better in-sample fit and stays the
 * model behind every reported plant kW. But its intercept is negative, so
 * extrapolated below the band T1 actually ran it says an idling chiller costs
 * less than nothing and staging up is always free. Gordon-Ng tends to a
 * positive no-load loss instead, which is what a real centrifugal does, so it
 * is the model the MPC uses to price STAGING decisions that leave the observed
 * per-machine load band.
 *
 * Scored on 28732 held-out minutes (2025-12-25 to 2025-12-31, never shuffled):
 *
 *   Gordon-Ng   MAE 5.2072 kW   MAPE 1.0547%   R2 0.91916
 *   affine      MAE 12.483 kW   MAPE 2.553%   R2 0.7952
 *
 * Observed per-machine load band (p1-p99): 68.44% - 92.59%.
 * Outside it BOTH models are extrapolating; only this one extrapolates in a
 * shape a chiller can actually have.
 */

/** Fleet-pooled coefficients (a1..a4), Kelvin basis. */
export const GORDON_NG_FLEET = [0.007361151947, 1421.286955, 0.002076791416, 0.005] as const;

/** Per-machine fits, for a future mixed-fleet model. Not used by the twin yet. */
export const GORDON_NG_UNITS: Array<{ unit: number; coeffs: number[] | null; n: number }> = [
  { unit: 1, coeffs: [0.1218290533, 911.3854538, 0.002160794699, 0.005], n: 17456 },
  { unit: 2, coeffs: [2.62983371e-25, 1095.519343, 0.002646489789, 0.005], n: 17273 },
  { unit: 3, coeffs: [4.893175655e-27, 1310.228673, 0.002344497212, 0.005], n: 44549 },
  { unit: 4, coeffs: [0.3276972064, 5.259623335e-08, 0.002308684804, 0.005], n: 27264 },
  { unit: 5, coeffs: [3.498097372e-09, 2200.265634, 0.0007007000712, 0.004999999997], n: 27275 }
];

export const GORDON_NG_FIT = {
  source: "data/processed/.t1-bms-cache.npz",
  trainDays: ["2025-11-30", "2025-12-24"],
  testDays: ["2025-12-25", "2025-12-31"],
  train: {"n": 105085, "maeKw": 5.4921, "rmseKw": 10.7453, "biasKw": -1.2888, "mapePct": 1.1277, "r2": 0.9389},
  heldOut: {"n": 28732, "maeKw": 5.2072, "rmseKw": 10.4682, "biasKw": -0.5774, "mapePct": 1.0547, "r2": 0.91916},
  affineTrain: {"n": 105085, "maeKw": 13.0862, "rmseKw": 17.5919, "biasKw": 11.1327, "mapePct": 2.7542, "r2": 0.83624},
  affineHeldOut: {"n": 28732, "maeKw": 12.483, "rmseKw": 16.6617, "biasKw": 11.2544, "mapePct": 2.553, "r2": 0.7952},
  observedPlrPct: {"p1": 68.44, "p99": 92.59},
  tChsMedianC: 7.57,
  tCdsMedianC: 28.48,
} as const;

const KELVIN = 273.15;
const RT_TO_KW = 3.517;

/**
 * Compressor power for one machine, kW.
 *
 * `qRt` is that machine's evaporator duty, `tChsC` its leaving chilled water
 * and `tCdsC` its entering condenser water.
 */
export function gordonNgChillerKw(qRt: number, tChsC: number, tCdsC: number): number {
  const [a1, a2, a3, a4] = GORDON_NG_FLEET;
  const q = Math.max(qRt, 0) * RT_TO_KW;
  const tChs = tChsC + KELVIN;
  const tCds = tCdsC + KELVIN;
  const dt = tCds - tChs;
  const num = q * dt + a1 * tCds * tChs + a2 * dt + a3 * q * q;
  const den = Math.max(tChs - a4 * q, 1);
  const kw = num / den;
  return Number.isFinite(kw) && kw > 0 ? kw : 0;
}

/** True when this per-machine load is outside the band the fit was estimated over. */
export function plrIsExtrapolated(plrPct: number): boolean {
  return plrPct < GORDON_NG_FIT.observedPlrPct.p1 || plrPct > GORDON_NG_FIT.observedPlrPct.p99;
}
