/**
 * Month-wide calibration of the T1 plant — GENERATED by
 * frontend/scripts/calibrateFromDataset.py from
 * T1_MVrawDataR2_2025_12_completed.xlsx. Do not hand-edit; re-run the script.
 *
 * Generated 2026-08-07 from 43,026 usable rows of 44,640
 * (Dec-31 excluded — the workbook's audit sheet flags DPM_CT_04_kW missing all
 * day; also excluded: off-nominal staging and startup rows below 1500 RT).
 *
 * This REPLACES the previous single-row (Dec-1 00:00) anchoring. Row 1 turned
 * out to be an outlier day: its CHWP and CT meters read ~22% above the month
 * norm, which is exactly the bias the old constants carried into every replay.
 *
 * Method — grey-box: the engine's equations are kept and only their constants
 * re-estimated. Benchmarked against gradient-boosted trees on the same blocked
 * folds; physics-structured least squares won (0.85% vs 1.18% MAE) and extra
 * model capacity made it worse, so no ML surrogate is used.
 *
 * Fit quality — blocked CV over 6 folds of 5 days each (curve refitted inside
 * each fold, so no fold sees its own data):
 *   per-fold plant kW MAE 1.04% / 0.52% / 0.88% / 1.21% / 0.92% / 0.75%  -> mean 0.89%
 *   in-sample bias -0.082%  MAE 0.832%
 *
 * NOT identifiable from this dataset, so NOT fitted (see stage 1 of the script):
 *   - pump affinity exponents: flow/pump spans only
 *     3.3% (CHWP) / 1.5% (CWP) p5->p95, so the
 *     cube law is retained on physics grounds. Pump power is accurate at the
 *     observed operating point but UNVALIDATED for large commanded VSD changes.
 *     A free fit of the exponent returns 1.65 (CHWP) and -0.65 (CWP) — the
 *     latter physically impossible for a pump, which is the tell.
 *   - evaporator-reset sensitivity: the CHWS setpoint moves only
 *     0.07 degC p5->p95; held at the literature 3 %/degC.
 */

/**
 * Default operating point — the month's MEDIAN, replacing the old row-1 boot
 * anchor. The twin now boots at a representative day instead of at Dec-1 00:00,
 * whose pump and tower meters sat ~22% above every other day of the month.
 */
export const DEFAULT_LOAD_RT = 3094.0816;
export const DEFAULT_CHWS_SP = 7.58;
export const DEFAULT_CW_DT_SP = 4.2631;
export const DEFAULT_CWS = 28.47;
export const DEFAULT_WET_BULB = 24.79;
/**
 * Reference outdoor RH at 31 degC dry-bulb. The workbook has no OAT/RH columns —
 * only the five WST wet-bulb sensors — so the twin's weather inputs parameterise
 * wet-bulb rather than measure it. This value is solved so the engine's Stull
 * estimate lands on the plant's median measured wet-bulb (24.79 degC),
 * which the tower-fan model now depends on. The old default (65 %RH) implied
 * 25.72 degC — about 0.93 degC too humid.
 */
export const DEFAULT_HUMIDITY_RH = 59.37;
/** Measured loop deltaT at that point — used to size CHWP staging flow. */
export const MEDIAN_LOOP_DELTA_T = 6.88;
/** Measured plant efficiency at that point (kW per RT). */
export const MEDIAN_PLANT_KW_PER_RT = 0.58498;

/**
 * Staging thresholds — the load each running unit actually carried before the
 * plant added another (99.9th percentile of the observed per-unit load with
 * three units running). T1 runs its chillers far harder than the shipped
 * 90%-of-nameplate rule assumed: three machines carry the plant to its monthly
 * peak, where the old 1125 RT threshold would have started a fourth.
 */
export const STAGE_RT_PER_CHILLER = 1184.1;
export const STAGE_FLOW_PER_CHWP = 490.1;

/** Chiller part-load curve, kW per running chiller (affine in load %). */
export const CH_KW_INTERCEPT = -29.412439;
export const CH_KW_SLOPE_PER_PCT = 6.664188;

/**
 * Condenser lift, fraction of chiller kW per degC of CWS above 29 degC.
 * Load and CWS are weather-correlated (r = +0.672), so a joint fit
 * attributes load to CWS: it returns 5.08 %/degC. This value is the
 * pooled WITHIN-load-bin slope (0.5%-wide bins), which holds load ~constant.
 * Still above the 1.5-3.0 %/degC literature range — residual confounding is
 * likely, so confirm with a CWS step test before closed-loop use.
 */
export const CONDENSER_LIFT_PER_DEGC = 0.045154;

/** Reference kW per running unit, at the plant's actual operating point. */
export const REF_CHILLER_KW_MONTH = 506.0820;
export const REF_CHWP_KW_MONTH = 19.5800;
export const REF_CWP_KW_MONTH = 54.4400;
export const REF_CT_KW_MONTH = 14.1000;

/** Reference flow per running pump (m3/h) at that same operating point. */
export const REF_CHWP_FLOW_MONTH = 454.75;
export const REF_CWP_FLOW_MONTH = 835.88;

/**
 * Per-unit kW trims — each unit's median draw while running, over the reference.
 * These absorb duty rotation: the Dec-16 step in plant kW is CWP-1/2 (~58 kW)
 * handing over to CWP-3/4/5 (~52 kW), not a change in any unit's behaviour.
 */
export const CH_TRIM_MONTH = [0.981303, 0.986579, 1.030169, 1.006872, 0.995076];
export const CHWP_TRIM_MONTH = [0.965781, 0.998468, 1.031154, 1.014811, 0.989785, 1.000000];
export const CWP_TRIM_MONTH = [1.060801, 1.061903, 0.959405, 0.956466, 0.961425, 1.000000];
export const CT_TRIM_MONTH = [0.907801, 0.879433, 0.936170, 0.929078, 1.347518];

/** Absolute median kW per unit while running (trim x reference). */
export const CH_UNIT_KW = [496.620000, 499.290000, 521.350000, 509.560000, 503.590000];
export const CHWP_UNIT_KW = [18.910000, 19.550000, 20.190000, 19.870000, 19.380000, 19.580000];
export const CWP_UNIT_KW = [57.750000, 57.810000, 52.230000, 52.070000, 52.340000, 54.440000];
export const CT_UNIT_KW = [12.800000, 12.400000, 13.200000, 13.100000, 19.000000];

/** Parasitic draw of STOPPED units (controls / oil heaters / meter noise). */
export const CH_STANDBY_KW_MONTH = [1.330000, 1.330000, 1.330000, 1.200000, 1.470000];
export const CHWP_STANDBY_KW_MONTH = [0.010000, 0.010000, 0.010000, 0.040000, 0.000000, 0.040000];
export const CWP_STANDBY_KW_MONTH = [0.020000, 0.020000, 0.020000, 0.040000, 0.020000, 0.030000];

/**
 * Tower fan speed as a fraction of the 70% reference:
 *   speed / 70% = CT_FAN_SPEED_COEFF[0] + CT_FAN_SPEED_COEFF[1] x approach
 * where approach = CWS - wet-bulb. Power still follows the cube fan law; only
 * the SPEED response is fitted, because fan speed itself is not instrumented
 * anywhere in the workbook — only the resulting VSD kW.
 *
 * The approach coefficient is NEGATIVE by construction: holding a tighter
 * approach takes more air, and a cool night (bigger approach at the same CWS)
 * takes less. Adding wet-bulb as a second regressor fits better (5.4% vs 8.0%
 * on tower kW) but flips that sign positive, which would tell an operator that
 * lowering the CWS setpoint SAVES fan power. The script refuses to emit a
 * non-negative coefficient for exactly that reason.
 *
 * Towers stay the weakest component of the fit (~8% MAE) but are only ~3.3% of
 * plant kW, so they contribute ~0.26% to the plant total.
 */
export const CT_FAN_SPEED_COEFF = [1.162602, -0.040031];

/** Duty order (most-run unit first) observed over the current regime. */
export const DUTY_ORDER_MONTH = {
  chiller: [3, 5, 4, 1, 2],
  chwp: [3, 5, 4, 1, 2, 6],
  cwp: [3, 5, 4, 1, 2, 6],
  ct: [4, 5, 2, 1, 3],
} as const;

/* ------------------- per-unit display channels (medians) ------------------ */

/**
 * Sensor offsets of a RUNNING unit against the plant headers (degC). Measured
 * per unit over the whole month — row 1 only ever saw CH-2/3/4 running, so it
 * could not characterise CH-1/5 at all, and those units are in the running set
 * under the month-observed duty order.
 */
export const CH_SENSOR_OFFSET_MONTH = {
  chwSt: [0.000000, 0.030000, -0.020000, -0.010000, 0.030000],
  chwRt: [-0.010000, 0.000000, 0.000000, 0.010000, -0.020000],
  cwSt: [-0.116667, -0.026667, 0.003333, -0.033333, 0.050000],
  cwRt: [-0.133333, -0.183333, 0.010000, -0.003333, 0.043333],
};

/** Stagnant readings of a STOPPED chiller (median while off). */
export const CH_STAGNANT_MONTH = [
  { chwSt: 10.23, chwRt: 15.45, cwSt: 23.09, cwRt: 31.20 },
  { chwSt: 9.99, chwRt: 15.43, cwSt: 23.35, cwRt: 24.95 },
  { chwSt: 15.00, chwRt: 16.50, cwSt: 26.00, cwRt: 29.00 },
  { chwSt: 9.53, chwRt: 19.19, cwSt: 24.65, cwRt: 24.23 },
  { chwSt: 17.74, chwRt: 18.83, cwSt: 25.08, cwRt: 24.70 },
];

/** Compressor-1 share of each chiller's DPM total. */
export const CH_CP1_SHARE_MONTH = [0.450039, 0.508721, 0.502560, 0.497683, 0.501302];

/** HL heat-load meter / DPM feeder meter, per compressor — HL reads ~6% low. */
export const HL_CP_RATIO_MONTH = [
  [0.931001, 0.927303],
  [0.936997, 0.936557],
  [0.934073, 0.938433],
  [0.939948, 0.938626],
  [0.943247, 0.930481],
];

/** VSD kW readout / DPM feeder meter, per pump. */
export const CHWP_VSD_RATIO_MONTH = [0.971279, 0.975354, 0.973930, 0.974255, 0.965795, 0.980000];
export const CWP_VSD_RATIO_MONTH = [0.992353, 0.991334, 0.987725, 1.002313, 0.994062, 0.980000];

/** Tower cell VSD kW as fractions of the tower's DPM meter (sum < 1). */
export const CT_CELL_KW_FRAC_MONTH = [
  [0.470312, 0.480743],
  [0.468000, 0.480488],
  [0.465644, 0.473485],
  [0.474809, 0.468992],
  [0.487029, 0.466667],
];

/** Tower cell temperature offsets against the plant CWS / CWR headers. */
export const CT_CELL_OFFSET_MONTH = {
  cwst: [[0.1900, 0.0933], [-0.0200, -0.0967], [0.0567, 0.0067], [0.0267, -0.1400], [0.5133, 0.4267]],
  cwrt: [[0.0433, 0.0900], [0.0700, 0.1367], [0.0600, 0.0800], [0.1100, 0.1000], [0.1300, 0.1667]],
};

/** Stagnant cell readings for a stopped tower. */
export const CT_STAGNANT_MONTH = {
  cwst: [28.53, 28.47],
  cwrt: [27.27, 27.45],
};

/** Per-chiller flow-meter trims against an even split of the loop / CW flow. */
export const CH_EVAP_FLOW_TRIM_MONTH = [0.980123, 0.982653, 1.001134, 0.999221, 0.999212];
export const CH_COND_FLOW_TRIM_MONTH = [0.986874, 1.004232, 1.010423, 0.994348, 0.994345];

/** Riser load split (% of building load) and hydronic flow fractions. */
export const RISER_LOAD_SHARE_MONTH = [31.713346, 23.058236, 23.734808, 21.402579];
export const RISER_FLOW_FRAC_MONTH = [0.292620, 0.199814, 0.325537, 0.182067];
export const RISER_ST_OFFSET_MONTH = [0.000000, 0.000000, 0.000000, 0.010000];
export const RISER_RT_OFFSET_MONTH = [0.001079, 0.001916, 0.002217, 0.001447];

/** Per-sensor wet-bulb bias against the five-sensor mean. */
export const WST_OFFSET_MONTH = [-0.456000, -0.002000, 0.026000, 0.388000, 0.016000];

/** Blocked-CV score, surfaced by the API /health and /schema endpoints. */
export const CALIBRATION_FIT = {
  rowsUsed: 43026,
  blockedCvMaePct: 0.8872,
  inSampleMaePct: 0.8316,
  inSampleBiasPct: -0.0817,
  regimeStartDay: 17,
} as const;
