/**
 * Cooling-tower approach, fitted to the T1 December trend — GENERATED by
 * `calibration/scripts/fitTowerApproach.py`. Do not hand-edit; re-run the
 * script and paste its shipped coefficients.
 *
 * What this replaces and why
 * --------------------------
 * The horizon simulator used to obtain condenser water temperature by
 * INVERTING the engine's fan law: assume a fan speed, ask what approach that
 * speed can hold. The site trends no fan-speed channel at all, so that law was
 * never fitted against observed fan speeds, and the inversion returned about
 * 2.7 K where the plant measured 4.64 K.
 *
 * That 2 K of approach error was worth roughly 5% of plant power — replaying
 * 2025-12-14 produced 12,767 kWh against a metered 13,923 kWh — and it drove
 * CWS to 26.8 °C, below the twin's calibrated 27.4–29.5 °C band, so every
 * horizon step flagged itself `extrapolated`.
 *
 * Scored against the same 2,879 fittable buckets, the constant it replaces is
 * worse than predicting the mean:
 *
 *   effective 2.7 K constant   MAE 0.922 K   bias −0.884 K   R² −2.609
 *   this fit, held-out days    MAE 0.103 K   bias −0.023 K   R²  0.932
 *
 * Held-out means the last seven days of the month, split on a whole-day
 * boundary and never shuffled.
 */

/** Approach is only observed over this range; the model is clamped to it. */
export const OBSERVED_APPROACH_C = { min: 1.51, max: 5.18 } as const;

/**
 * Wet bulbs December actually presented. The fit is a straight line through a
 * 4 K span, so it degenerates quickly outside it — at 30 °C wet bulb the raw
 * model returns −0.47 K, which is not a temperature difference a tower can
 * have. `fittedApproachC` clamps, but a clamped value is a fabricated one
 * unless somebody is told, so callers should check `approachIsExtrapolated`
 * and surface it the same way `assessCalibrationEnvelope` surfaces the rest.
 */
export const VALID_WET_BULB_C = { min: 23.17, max: 27.18 } as const;

/** Whether these conditions are outside the band the fit was estimated over. */
export function approachIsExtrapolated(wetBulbC: number): boolean {
  return wetBulbC < VALID_WET_BULB_C.min || wetBulbC > VALID_WET_BULB_C.max;
}

/**
 * `approach = intercept + perWetBulbK·wetBulb + perKiloRt·(loadRt/1000)`
 *
 * Both signs are physically right. Approach NARROWS as wet bulb rises
 * (r = −0.918 — the saturation enthalpy curve steepens, so the tower rejects
 * heat more readily) and WIDENS with load (more heat through the same air).
 *
 * The load term earns almost nothing statistically — December's load barely
 * moved, so it is worth about 0.006 K — but it is kept because without it the
 * tower cannot see staging at all: shedding a chiller would leave CWS
 * untouched and the MPC would optimise against an inert condenser.
 */
export const TOWER_APPROACH_FIT = {
  intercept: 21.349124,
  perWetBulbK: -0.787621,
  perKiloRt: 0.584858,
  /** Honest accuracy: scored on days the fit never saw. */
  heldOut: { n: 576, maeK: 0.103, rmseK: 0.127, biasK: -0.023, r2: 0.932 },
  inSample: { n: 2879, maeK: 0.153, rmseK: 0.203, biasK: 0.0, r2: 0.863 },
  source: 'data/processed/t1_2025_12_15min.json',
  rowsUsed: 2879,
} as const;

/**
 * Approach the towers actually hold at these conditions, in K.
 *
 * Site-calibrated but envelope-bound: December only ever presented wet bulbs of
 * 23.2–27.2 °C at 2,480–3,565 RT, so the clamp is doing real work outside that
 * box. `assessCalibrationEnvelope` is what reports the extrapolation.
 */
export function fittedApproachC(wetBulbC: number, loadRt: number): number {
  const raw =
    TOWER_APPROACH_FIT.intercept +
    TOWER_APPROACH_FIT.perWetBulbK * wetBulbC +
    TOWER_APPROACH_FIT.perKiloRt * (loadRt / 1000);
  return Math.min(OBSERVED_APPROACH_C.max, Math.max(OBSERVED_APPROACH_C.min, raw));
}
